# Changes here will be overwritten by Copier
_commit: 0.1.3
_src_path: template
project_authors:
- '  {name = "m09", email = "142691+m09@users.noreply.github.com"},'
project_description: CLI to list and create GitHub issues.
project_homepage: https://github.com/shuuchuu/ghcli
project_id: ghcli
project_license: Apache-2.0
project_name: ghcli
tools:
- devcontainer
- doit
- pytest
